### ISSUE TITLE
Uable to (re)authenticate against iobroker - wrong configuration cookie was not set

### ISSUE THREAD

**Issue by evilbaschdi** [nokxs/iobroker-javascript-vs-code-extension#167]
**Describe the bug**
Coming from an existing environment working with this extension I tried to authenticate against my iobroker this morning and run into the following issue:

2025-03-16T09:01:42.658Z INFO LoginCredentials GetPassword: Get password from storage
2025-03-16T09:01:42.684Z INFO IobrokerConnectionService Connection was not possible due to erorr: "Cookie was not set"
2025-03-16T09:01:42.684Z ERROR Message Could not connect to ioBroker. Check your '.iobroker-config.json' for wrong configuration: Cookie was not set.

I seems like the issue is caused by something that might have changed inside vs code. Bacause I also tried older extension versions and other devices - same problem.

**To Reproduce**
1. Open local folder connected to the iobroker
2. Open that folder inside VS Code
3. Wait for the dialog to enter a new password - that also should not appear cause of having "autoReconnect" set to true
4. enter the (correct) password
5. Issue occurs

**Expected behavior**
Extension should read the password from secret store or take the new one entered and authenticate against iobroker.

[debug.log](https://github.com/user-attachments/files/19270336/debug.log)

**Version information (please complete the following information):**
 - Extension version: 1.8.1
 - VS Code version: 1.98.2
 - ioBroker admin version: 7.6.2
 - ioBroker nodejs version: 22.14.0
 - ioBroker javascript adapter version: 7.0.6

**Comment by patricknitsch** [comment]
Same problem here.

**Comment by nokxs** [comment]
After updating admin adapter I got the problem myself. It seems the authentication process works now differently. I try to fix it the next few days.

**Comment by UrsKobler** [comment]
Thank you for developing this brilliant plugin for VS Code.

It looks like something has changed in the admin adapter regarding the OAuth 2.0 role.

Since upgrading the admin adapter version 7.4.10 to 7.6.3, a remote connection from the integrated development environment "Visual Studio Code" is no longer possible!

It would be great if you could make the necessary adjustments.

I wish you the best of luck.

**Comment by nokxs** [comment]
I've had some time to dig into the issue. Admin Adapter changed its authentication workflow to OAuth, which means I have to change quite a few things to get it working again. 

The only way working around this problem is disabling authentication until I manage to fix the issue.

**Comment by UrsKobler** [comment]
Since the target system is being developed on the local network, temporarily suppressing the authentication process seems like a sensible workaround.

Would it be possible to provide such a temporary workaround to users until a definitive solution can be implemented?

**Comment by nokxs** [comment]
I just got it working locally with some hacks. Give me a little more time to provide a clean solution, which also works with older versions.

**Comment by nokxs** [comment]
I still need to test the changes a little bit more before merging, but so far it is looking good :-)

**Comment by nokxs** [comment]
Version 1.8.2 fixes the problem for me. Could you please reply and let me know if it is also fixed for you?

@UrsKobler Sorry for not replying to your idea, but it as it looks now no workaround is necessary :-)

**Comment by evilbaschdi** [comment]
yes!! it's running again. the problem is solved!

**Comment by UrsKobler** [comment]
@nokxs

Congratulations and respect! 

You're a superhero and were able to successfully resolve the issue in the Oauth 2.0 workflow without a temporary workaround!

I've just successfully tested the new iobroker plugin release v1.8.2. This latest release now also works again with the latest admin adapter version 7.6.3.

I thank you for the professional and quick resolution of the issue.

I wish you a relaxing weekend.

Best regards,
Kobi

**Comment by nokxs** [comment]
Thank you very much for the positive comments, and I am also glad that the problem could be resolved relatively quickly. I'm also happy, if you star the repository to show its relevance.

The issue is now resolved amd will be closed.

**Comment by lzimmermann** [comment]
HI all, though this is closed, I am on 1.8,3 and still have issues - vscode does not connect to iob any more, issue startet as reported in this track - nayone else still having this porblem?

**Comment by nokxs** [comment]
@lzimmermann  could you create a new issue for this and attach debug logs, so I can investigate the issue?
